### ISSUE TITLE
How to use this in Java

### ISSUE THREAD

**Issue by sleighsoft** [fracpete/snowball-stemmers-weka-package#1] opened 2015-07-14 12:42 UTC
I added the stemmer to my maven project with your provided maven configuration.
I try to do the following

```
import weka.core.stemmers.SnowballStemmer;

public class test {

    public static void main(String[] args) {
    SnowballStemmer snowballStemmer = new SnowballStemmer();
    System.out.println(snowballStemmer.stem("Employee"));
    }
}
```

Trying to use it with the `StringToWordVector` also fails

```
StringToWordVector filter = new StringToWordVector();
    filter.setStemmer(new SnowballStemmer());
```

It fails with the following error

```
java.lang.NullPointerException
    at weka.core.ClassCache.initFromManifest(ClassCache.java:248)
    at weka.core.ClassCache.initFromJar(ClassCache.java:293)
    at weka.core.ClassCache.initFromClasspathPart(ClassCache.java:351)
    at weka.core.ClassCache.initialize(ClassCache.java:372)
    at weka.core.ClassCache.<init>(ClassCache.java:111)
    at weka.core.ClassDiscovery.initCache(ClassDiscovery.java:447)
    at weka.core.ClassDiscovery.clearCache(ClassDiscovery.java:481)
    at weka.core.ClassDiscovery.clearClassCache(ClassDiscovery.java:490)
    at weka.core.WekaPackageManager.refreshGOEProperties(WekaPackageManager.java:1163)
    at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1154)
    at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1065)
    at weka.gui.GenericObjectEditor.determineClasses(GenericObjectEditor.java:177)
    at weka.gui.GenericObjectEditor.<clinit>(GenericObjectEditor.java:247)
    at weka.core.stemmers.SnowballStemmer.initStemmers(SnowballStemmer.java:264)
    at weka.core.stemmers.SnowballStemmer.setStemmer(SnowballStemmer.java:355)
    at weka.core.stemmers.SnowballStemmer.<init>(SnowballStemmer.java:122)
    at weka.core.stemmers.SnowballStemmer.<init>(SnowballStemmer.java:110)
    at classifier.test.main(test.java:19)
```

Am I supposed to use a different constructor/class?
Could you provide a working example?

Thanks in advance :)

**Comment by fracpete** [comment] 2015-07-15 02:12
There seems to be a problem with your classpath, from the looks of it a jar with no manifest file?
However, I just made a new release available, 1.0.1, and added some usages to the README.md as well. Please try again with that.

**Comment by sleighsoft** [comment] 2015-07-15 11:56
I do have `snowball-stemmers-weka-package-1.0.1.jar` in my Java Build Path under Maven Dependencies.
I still get the following error when trying to use your standalone code example.

```
Exception in thread "main" java.lang.NoSuchMethodError: org.tartarus.snowball.ext.porterStemmer.eq_s(ILjava/lang/String;)Z
    at org.tartarus.snowball.ext.porterStemmer.stem(porterStemmer.java:639)
    at classifier.test2.main(test2.java:13)
``
```

**Comment by fracpete** [comment] 2015-07-16 02:18
Sorry, I can't replicate this. I've created an example Maven project that uses the dependency and the example usage and it works fine. Email me at [ fracpete at waikato dot ac dot nz ] and I can send it to you.

**Comment by sleighsoft** [comment] 2015-07-16 22:48
Your sample project works fine.
But when I apply the exact same settings in my project it results in a crash.
I have a new stack trace. Maybe this helps.

```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.tartarus.snowball.ext.porterStemmer.eq_s(ILjava/lang/String;)Z
    at org.tartarus.snowball.ext.porterStemmer.stem(porterStemmer.java:639)
    at classifier.test.main(test.java:10)
    ... 6 more
```

**Comment by fracpete** [comment] 2015-07-17 02:07
Do you have packages installed using Weka's package manager? If so, disable these for the time being (simply rename the $HOME/wekafiles directory to something else). Maybe the problem is due to a conflicting library.

**Comment by sleighsoft** [comment] 2015-07-17 14:29
I have finally determined the culprit.
I have the following elasticsearch dependency in my .pom file which causes the invocation error.

```
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>1.5.0</version>
        </dependency>
```

I could not yet determine the actual source of fault inside the dependency hierarchy of elasticsearch.
Also tested with 1.7.0 and still not working.

**Comment by sleighsoft** [comment] 2015-07-17 21:49
The No-Weka part seems to work with this exclusion.

```
       <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>1.7.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>lucene-analyzers-common</artifactId>
                    <groupId>org.apache.lucene</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

The `StringToWordVector` still fails but with the error of my first post here.

**Comment by fracpete** [comment] 2015-07-18 02:15
The initial exception `java.lang.NullPointerException at weka.core.ClassCache.initFromManifest(ClassCache.java:248)` must stem from a jar in your project that does not have a manifest. Weka's package manager analyzes the path and seems to stumble across that. That is a Weka problem (report that on the Weka mailing list) and I will close this issue now.

**Closed as completed by fracpete** 2015-07-18 02:15 UTC
